### ISSUE TITLE
not found draw_sem_seg_by_cv2_sum 

### ISSUE THREAD

**Issue by PXinTao** [dengxl0520/MemSAM#1]
"Hello, I did not find the draw_sem_seg_by_cv2_sum function in **utils.tools**, and I am getting an error when running train. Please help with this issue.

Traceback (most recent call last):
File "F:\MemSAM-main\MemSAM-main\train_video.py", line 20, in <module>
from utils.evaluation import get_eval
File "F:\MemSAM-main\MemSAM-main\utils\evaluation.py", line 16, in <module>
from utils.visualization import visual_segmentation, visual_segmentation_npy, visual_segmentation_binary, visual_segmentation_sets, visual_segmentation_sets_with_pt
File "F:\MemSAM-main\MemSAM-main\utils\visualization.py", line 11, in <module>
from .utils.tools import draw_sem_seg_by_cv2_sum
ModuleNotFoundError: No module named 'utils.utils'"

**Comment by dengxl0520** [comment]
You can delete that import, it is only used to visualize the results. Subsequent updates will fix it.

**Comment by PXinTao** [comment]
Thank you



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/06/2024 00:41 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [dengxl0520/MemSAM] not found draw_sem_seg_by_cv2_sum (Issue #1) |

You can delete that import, it is only used to visualize the results. Subsequent updates will fix it.
