### ISSUE TITLE
There is a typographical error in Figure 3 of the paper.

### ISSUE THREAD

**Issue by Qian8625** [dengxl0520/MemSAM#17]
![image](https://github.com/user-attachments/assets/75873571-e14e-4df3-a7c5-4cf8c8838b8a)

The Prompt Encoder in Figure 3 is written as "Prompt Eecoder". An interesting typo, I thought it was some new module.

But the original text of the paper is “ The SAM component adopts an architecture identical to the original SAM, composed of an image encoder, a prompt encoder, and a mask decoder. ”

**Comment by Qian8625** [comment]
In addition, I found that the images on the author's GIthub homepage are correct, but when I downloaded the paper from the official link of CVPR (https://openaccess.thecvf.com/content/CVPR2024/papers/Deng_MemSAM_Taming_Segment_Anything_Model_for_Echocardiography_Video_Segmentation_CVPR_2024_paper.pdf), this issue occurred. 

It seems that the author also noticed this typographical error and hopes to correct it as soon as possible, so as not to affect other readers.

**Comment by dengxl0520** [comment]
Thanks for the friendly heads up. We have found some errors in our paper and we will consider releasing an updated corrected version.
