### ISSUE TITLE
Disscusion about the selection between SAM, MedSAM and SAM-Med2d

### ISSUE THREAD

**Issue by jinggqu** [dengxl0520/MemSAM#4]
Thanks for your valuable work. However, I have several questions about your work:

1. Why did you choose the original SAM from facebook instead of other variants? As far as I know, there are two SAMs ([MedSAM](https://github.com/bowang-lab/MedSAM) and [SAM-Med2D](https://github.com/OpenGVLab/SAM-Med2D)) that are trained on large-scale medical image datasets instead of natural image datasets. Even more, there is also a light-weighted SAM model ([LiteMedSAM](https://github.com/bowang-lab/MedSAM/tree/LiteMedSAM)).
2. Have you compared the segmentation performance of the above models?
3. I found that the SAM cannot inference images by batch, how did you solve this problem? (Iterating images one by one?)

Anyway, thank you for open sourcing this novel work.

**Comment by dengxl0520** [comment]
Thank you for your attention.
1. Initially, we chose to use SAMUS for reasons of computing resources, and LiteMedSAM seems to be the later. Moreover, SAMUS is better suited to our task(Echocardiography Segmentation).
2. For experiments please read our [paper](https://github.com/dengxl0520/MemSAM/blob/main/paper.pdf).
3. For MemSAM, inference should be one by one.
