### ISSUE TITLE
CAMUS dataset

### ISSUE THREAD

**Issue by kimsekeun** [dengxl0520/MemSAM#5]
Dear author, 
1. CAMUS dataset only provides ED, ES annotations, could you please let me know where all frame annotated dataset is offered for evaluation? 
2. Could you please let me know about camus split indexes for training, val, and test set?
3. For SonoSAM, the author of sonosam did not opened their code how did you evaluate on this method? and it needs point prompt for segmentation.

**Comment by dengxl0520** [comment]
Thank you for your attention.
1. Official [CAMUS ](https://www.creatis.insa-lyon.fr/Challenge/camus/index.html) project has published full frame annotations.
2. See [here](https://github.com/dengxl0520/MemSAM/blob/main/utils/preprocess_camus.py).
3. We have only reproduced SonoSAM's method on our data, and the results presented are based on our reproduction only. The point prompts are randomly sampled from Ground Truth.
