### ISSUE TITLE
CAMUS dataset preprocess

### ISSUE THREAD

**Issue by Salvation4** [dengxl0520/MemSAM#7]
when i run the untils/preprecocess_camus.py, it shows that there is a bug
![2024-06-08_00001](https://github.com/dengxl0520/MemSAM/assets/82426583/cc298127-8740-4fae-9e20-4290a93dc03d)
i only change the path in the preprocess_camus.py, and here is the code i have change
![2024-06-08_00002](https://github.com/dengxl0520/MemSAM/assets/82426583/a2d8b477-88ec-494c-8d79-117f7e2ca519)
I think maybe there are some bugs in this code, or I did not use the file in the right way...
plz help me

**Comment by dengxl0520** [comment]
This should be an error triggered by the Python version, please use Python 3.10 or above.
